### ISSUE TITLE
react-web start error

### ISSUE THREAD

**Issue by fengyun2** [yuanyan/react-native-web-example#8]
# Development OS: Linux
#### Install react-native
1. `npm install -g react-native-cli`
2. `react-native init react_native_for_web`
#### Install react-web
1. `npm install react-web-cli -g`
2. `react-web init react_native_for_web`
3. `npm start`
4. `react-web start`
5. `react-web bundle`
### BUG
- when run `react-web start`
  ERROR in Path must be a string. Received undefined

dependices on

``` json
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-native": "0.30.0",
    "react-web": "0.3.2"
```

**Comment by daanluu** [comment]
Do how you  resolved this ?
